### ISSUE TITLE
Installing with Gemfile

### ISSUE THREAD

**Issue by monocrstl** [z64/osu-api#17]
_Note: I don't know if this is an actual "bug" or if I'm just a newbie writing a useless issue._ 

I was trying to install osu-api with Gemfile and the [Installation](https://github.com/z64/osu-api#installation) section says:

>Add this line to your application's Gemfile:
>```ruby
>gem "osu-api", github: "https://github.com/z64/osu-api"
>```
So I did it:
```ruby
# frozen_string_literal: true
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "osu-api", github: "https://github.com/z64/osu-api"
```
Running `bundle install`...
```
$ bundle install

fatal: repository 'https://github.com/https://github.com/z64/osu-api/' not found
```
I tried removing the `git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }` line. It didn't work. So what I did was:
```ruby
# frozen_string_literal: true
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "osu-api", github: "z64/osu-api"
```
And it worked!

===

This also works:

```ruby
# frozen_string_literal: true
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "osu-api", git: "https://github.com/z64/osu-api.git"
```

**Comment by z64** [comment]
Indeed, the README is wrong and it should be using the `git` resolver, not `github`. In which case, the `git_source` line isn't necessary.
